--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Davs125/Casino
build-by-default: true
branches:
- main
projects:
  Casino:
    path: ""
    icon: "casino.png"
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
    lint:
      phpstan: false 
...
